import json
import csv
import io
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from database.mongodb import get_database, serialize_doc
from database.schemas import ExportRequest, ExportResponse
from api.auth import get_current_user

router = APIRouter(prefix="/api/export", tags=["export"])


async def _gather_analysis_data(analysis_id: str, user_id: str) -> dict:
    db = get_database()

    analysis = await db.analyses.find_one({"_id": analysis_id, "user_id": user_id})
    if not analysis:
        return {}

    pp_cursor = db.pain_points.find({"analysis_id": analysis_id}).sort("rank", 1)
    pain_points = await pp_cursor.to_list(length=50)

    persona_cursor = db.personas.find({"analysis_id": analysis_id})
    personas = await persona_cursor.to_list(length=20)

    ad_cursor = db.ad_assets.find({"analysis_id": analysis_id})
    ad_assets = await ad_cursor.to_list(length=200)

    competitor_cursor = db.competitors.find({"analysis_id": analysis_id})
    competitors = await competitor_cursor.to_list(length=20)

    return {
        "analysis": serialize_doc(analysis),
        "pain_points": [serialize_doc(pp) for pp in pain_points],
        "personas": [serialize_doc(p) for p in personas],
        "ad_assets": [serialize_doc(ad) for ad in ad_assets],
        "competitors": [serialize_doc(c) for c in competitors],
    }


def _generate_pdf_content(data: dict) -> str:
    lines = []
    lines.append("=" * 60)
    lines.append("PainToAd AI - Marketing Intelligence Report")
    lines.append("=" * 60)
    lines.append("")

    analysis = data.get("analysis", {})
    lines.append(f"Topic: {analysis.get('topic', 'N/A')}")
    lines.append(f"Industry: {analysis.get('industry', 'N/A')}")
    lines.append(f"Status: {analysis.get('status', 'N/A')}")
    lines.append(f"Created: {analysis.get('created_at', 'N/A')}")
    lines.append("")

    lines.append("-" * 60)
    lines.append("EXECUTIVE SUMMARY")
    lines.append("-" * 60)
    lines.append("(Generated insight narrative)")
    lines.append("")

    lines.append("-" * 60)
    lines.append("PAIN POINTS")
    lines.append("-" * 60)
    for pp in data.get("pain_points", []):
        lines.append(f"#{pp.get('rank', '?')} [{pp.get('emotion_type', 'N/A')}] "
                      f"(score: {pp.get('emotion_score', 0)}/10, freq: {pp.get('frequency', 0)})")
        lines.append(f"   {pp.get('text', 'N/A')}")
        for q in pp.get("example_quotes", []):
            lines.append(f"   Quote: \"{q}\"")
        lines.append("")

    lines.append("-" * 60)
    lines.append("BUYER PERSONAS")
    lines.append("-" * 60)
    for p in data.get("personas", []):
        lines.append(f"Name: {p.get('name', 'N/A')}")
        lines.append(f"  Age: {p.get('age_range', 'N/A')} | Occupation: {p.get('occupation', 'N/A')}")
        lines.append(f"  Revenue Potential: {p.get('revenue_potential', 'N/A')}")
        lines.append(f"  Best Channels: {', '.join(p.get('best_channels', []))}")
        lines.append(f"  Language: {p.get('language_preference', 'N/A')}")
        lines.append(f"  Core Pain: {p.get('core_pain', 'N/A')}")
        lines.append(f"  What They Want: {p.get('what_they_want', 'N/A')}")
        lines.append("")

    lines.append("-" * 60)
    lines.append("AD COPY BY PERSONA")
    lines.append("-" * 60)
    grouped = {}
    for ad in data.get("ad_assets", []):
        pid = ad.get("persona_id", "unknown")
        if pid not in grouped:
            grouped[pid] = []
        grouped[pid].append(ad)

    for pid, ads in grouped.items():
        persona = next((p for p in data.get("personas", []) if p.get("id") == pid), {})
        lines.append(f"\nPersona: {persona.get('name', pid)}")
        for ad in ads:
            lines.append(f"  [{ad.get('channel', 'N/A').upper()}] ({ad.get('language', 'english')})")
            lines.append(f"  {ad.get('content', 'N/A')}")
            lines.append(f"  CTR Score: {ad.get('ctr_score', 0)}/10")
            lines.append("")

    lines.append("-" * 60)
    lines.append("COMPETITOR ANALYSIS")
    lines.append("-" * 60)
    for c in data.get("competitors", []):
        lines.append(f"Competitor: {c.get('competitor_name', 'N/A')}")
        for w in c.get("weaknesses", []):
            lines.append(f"  - {w}")
        for ad in c.get("opportunity_ads", []):
            lines.append(f"  Attack Ad: {ad}")
        lines.append("")

    lines.append("=" * 60)
    lines.append("Report generated by PainToAd AI")
    lines.append("=" * 60)

    return "\n".join(lines)


def _generate_csv_content(data: dict) -> str:
    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow(["Section", "Type", "Content", "Score", "Channel", "Language"])

    for pp in data.get("pain_points", []):
        writer.writerow([
            "Pain Point",
            pp.get("emotion_type", ""),
            pp.get("text", ""),
            pp.get("emotion_score", ""),
            "",
            "",
        ])

    for p in data.get("personas", []):
        writer.writerow([
            "Persona",
            p.get("revenue_potential", ""),
            f"{p.get('name', '')} - {p.get('core_pain', '')}",
            "",
            ",".join(p.get("best_channels", [])),
            p.get("language_preference", ""),
        ])

    for ad in data.get("ad_assets", []):
        writer.writerow([
            "Ad Copy",
            ad.get("channel", ""),
            ad.get("content", ""),
            ad.get("ctr_score", ""),
            ad.get("channel", ""),
            ad.get("language", ""),
        ])

    return output.getvalue()


@router.post("/generate")
async def export_analysis(
    request: ExportRequest,
    current_user: dict = Depends(get_current_user),
):
    try:
        data = await _gather_analysis_data(request.analysis_id, current_user["id"])
        if not data:
            raise HTTPException(status_code=404, detail={"error": "Not found", "detail": "Analysis not found"})

        format_type = request.format.lower()

        if format_type == "json":
            content = json.dumps(data, indent=2, default=str)
            filename = f"pain2ad_export_{request.analysis_id}.json"
            return ExportResponse(
                content=content,
                format="json",
                filename=filename,
            )

        elif format_type == "csv":
            content = _generate_csv_content(data)
            filename = f"pain2ad_export_{request.analysis_id}.csv"
            return ExportResponse(
                content=content,
                format="csv",
                filename=filename,
            )

        elif format_type == "pdf":
            content = _generate_pdf_content(data)
            filename = f"pain2ad_export_{request.analysis_id}.txt"
            return ExportResponse(
                content=content,
                format="pdf",
                filename=filename,
            )

        else:
            raise HTTPException(
                status_code=400,
                detail={"error": "Invalid format", "detail": f"Supported formats: json, csv, pdf. Got: {format_type}"},
            )

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail={"error": "Export failed", "detail": str(e)})


@router.get("/formats")
async def get_supported_formats():
    return {
        "formats": [
            {"format": "json", "description": "Full structured JSON export"},
            {"format": "csv", "description": "Pain points and ad copy as CSV rows"},
            {"format": "pdf", "description": "Formatted text report with all sections"},
        ]
    }
